export const ACCESS_TOKEN = "accessToken"; //NOMBRE PARA ALMACENAR EL TOKEN EN EL LOCAL STORAGE
export const REFRESH_TOKEN = "refreshToken"; //NOMBRE PARA ALMACENAR EL REFRESH TOKEN EN EL LOCAL STORAGE
